//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Location { get; set; }
        public System.DateTime Start_Time { get; set; }
        public string Type { get; set; }
        public int Duration_in_hours { get; set; }
        public string Description { get; set; }
        public string Other_Details { get; set; }
        public string Invite_By_Email { get; set; }
    }
}
